project_id = "azzyyzympmwrwrjburer"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = []
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322

[storage]
enabled = true
port = 54323

[edge_functions]
enabled = true
port = 54325

[functions.process-brain-dump]
verify_jwt = false